# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: TestServiceConnectVala
  backendConfig: '$(System.DefaultWorkingDirectory)/deployments/dev/versions.tf'
steps:

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.11'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd $(System.DefaultWorkingDirectory)/deployments/dev/
      terraform init -backend-config='$(System.DefaultWorkingDirectory)/deployments/dev/versions.tf'
    displayName: 'Terraform init'  