# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: TestServiceConnectVala
steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: $(subscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
    addSpnToEnvironment: true
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  inputs:
    terraformVersion: '1.4.2'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |

      cd $(System.DefaultWorkingDirectory)/deployments/dev/
      terraform init -reconfigure
    displayName: 'Terraform init'  

