# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: TestServiceConnectVala
steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: $(subscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId" 
     
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
    
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"

      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscription"
    addSpnToEnvironment: true

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  inputs:
    terraformVersion: '1.4.2'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(ARM_SUBSCRIPTION_ID)
      az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET)  --tenant $(ARM_TENANT_ID)
      cd $(System.DefaultWorkingDirectory)/deployments/dev/
      terraform init -reconfigure
    displayName: 'Terraform init'  

