trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'infra_dev_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'